class AppException(Exception):
    pass


class UnexpectedError(AppException):
    pass
